#!/bin/sh
## Set defaults
ipfw_divert=1001
ipfw_LAN=1500
port_inet=ppp0
port_LAN=en1
host_LAN=10.7.8.8

if [ "$1" = "" ]
then
  ## No arguments given!
  echo "Usage: $0 [divert_ipfw_pos] [LAN_allow_ipfw_pos] <start | stop | status>"
  exit
elif [ $# = 3 ]
then
  ## All arguments given
  ipfw_divert="$1"
  ipfw_LAN="$2"
  mode="$3"
elif [ $# = 2 ]
then
  ## Only one firewall position given
  ipfw_divert="$1"
  ipfw_LAN="$1"+10
  mode="$2"
elif [ $# = 1 ]
then
  ## Most common usage - mode provided, defaults will be used
  mode="$1"
fi

if [ "$mode" = "status" ]
then
  sudo ps ax | grep natd | grep -v grep
  echo
  sudo ipfw show
  echo
  sudo sysctl net.inet.ip.forwarding
  exit

elif [ "$mode" = "stop" ]
then
  ## Stop ipforwarding
  sudo sysctl -w net.inet.ip.forwarding=0

  ## Remove firewall rules
  sudo ipfw "$ipfw_divert" delete
  sudo ipfw "$ipfw_LAN" delete
  sudo ipfw 1750 delete

  ## Stop natd
  pidfile="${PIDFILE:=/var/run/natd.pid}"
  pid=""
  if [ -f "${pidfile}" ]; then
    pid=$(head -1 "${pidfile}")
    if ! sudo kill -3 "${pid}" 2> /dev/null; then
      echo "Cannot quit natd using pid in file $pidfile"
      pid=""
#      rm -f "${pidfile}"
    fi
  fi

  if [ -n "${pid}" ]; then
    echo "natd stopped, pid: ${pid}"
  else
    echo "There was an error stopping natd"
  fi
  exit

elif [ "$mode" = "start" ]
then
  sudo natd -l -interface "$port_inet" -use_sockets -same_ports -unregistered_only -dynamic -clamp_mss -enable_natportmap -natportmap_interface "$port_LAN" -redirect_port tcp $host_LAN:smtp smtp -redirect_port tcp $host_LAN:http http
  sudo ipfw add "$ipfw_divert" divert natd all from any to any via "$port_inet"
  sudo ipfw add "$ipfw_LAN" allow tcp from any to any in recv "$port_LAN"
  sudo ipfw add 1750 allow tcp from any to $host_LAN smtp in via "$port_inet"
  sudo ipfw add 1750 allow tcp from any to $host_LAN http in via "$port_inet"
  sudo sysctl -w net.inet.ip.forwarding=1
  exit
fi
